version: '3.8'
 
services:
  app-staging:
    image: flask-task-api:latest
    container_name: flask-staging
    ports:
      - '5001:5000'
    environment:
      - FLASK_ENV=staging
    networks:
      - devops-net
    restart: unless-stopped
 
networks:
  devops-net:
    external: true

grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - devops-net
    restart: unless-stopped

volumes:
  grafana_data: