sonar.projectKey=flask-task-api
sonar.projectName=Flask Task API
sonar.sources=app
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11
sonar.qualitygate.wait=true
